version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project
    container_name: project
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/config/supervisord.ini:/etc/supervisor.d/supervisord.ini
      - ./.docker/cron/crons:/etc/crontabs/www-data
      - ./.docker/config/default.conf:/etc/nginx/http.d/default.conf
      - ./.docker/config/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
      - ./.docker/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - local
  db:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - local
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - local
networks:
  local:
    driver: bridge
